import { clientLog } from "@asm/config/debug";
import type { PostsPage, ResponsesPage } from "@asm/db";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import type { InfiniteData } from "@tanstack/react-query";

import { useToast } from "@/lib/gooey-toast";
import {
  applyResponseCountDeltaToCaches,
  forceInvalidatePostFeeds,
} from "@/lib/posts/cache-sync";

import { submitPost, updatePostMentions } from "./actions";

interface PostInput {
  content: string;
  hnStory?: {
    storyId: number;
    title: string;
    url?: string;
    by: string;
    time: number;
    score: number;
    descendants: number;
  };
  isGust?: boolean;
  mediaIds: string[];
  mentions: string[];
  // When set, this post is a response to that post.
  parentPostId?: string;
  tags: string[];
}

export function useSubmitPostMutation() {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const mutation = useMutation({
    mutationFn: async (input: PostInput) => {
      const payload = {
        content: input.content,
        hnStory: input.hnStory,
        isGust: input.isGust ?? false,
        mediaIds: input.mediaIds,
        mentions: Array.isArray(input.mentions)
          ? input.mentions.filter(Boolean)
          : [],
        parentPostId: input.parentPostId,
        tags: input.tags,
      };

      const response = await submitPost(payload);
      if (!response) {
        throw new Error("Failed to create post");
      }
      return response;
    },
    onError(error) {
      clientLog.error("Post creation error:", error);
      toast({
        description: "Couldn't create your post, try again?",
        variant: "destructive",
      });
    },
    onSuccess: async (newPost) => {
      // A response is a first-class post: it lands in its parent's thread and
      // in the timeline feeds (home + profile Posts), so refresh those caches.
      if (newPost.parentPostId) {
        const parentId = newPost.parentPostId;
        // The thread list is cached and streamed per thread ROOT, so a nested
        // response lands under its parent in the same cache every viewer of
        // the post shares.
        const threadRootId = newPost.rootPostId ?? parentId;
        const responseFilter = { queryKey: ["responses", threadRootId] };
        await queryClient.cancelQueries(responseFilter);
        queryClient.setQueriesData<InfiniteData<ResponsesPage, string | null>>(
          responseFilter,
          (oldData) => {
            if (!oldData?.pages[0]) {
              return oldData;
            }
            return {
              pageParams: oldData.pageParams,
              pages: [
                {
                  previousCursor: oldData.pages[0].previousCursor,
                  responses: [newPost, ...oldData.pages[0].responses],
                },
                ...oldData.pages.slice(1),
              ],
            };
          }
        );
        // The count shown on a card is its DIRECT responses, so a nested
        // response bumps its immediate parent, not the thread root.
        applyResponseCountDeltaToCaches(queryClient, parentId, 1);
        queryClient.invalidateQueries({ queryKey: ["post", threadRootId] });
        // Responses appear in Following / For You / Latest and the author's
        // Posts tab, so refresh those feeds too.
        forceInvalidatePostFeeds(queryClient);
        toast({
          description: "Your response is live",
          duration: 4000,
          title: "Response Published",
        });
        return;
      }

      // Gusts live on the dedicated /gusts feed, not the home "for-you" feed
      // (which filters isGust=false server-side). Only prepend regular posts
      // to the home feed cache; gusts are invalidated separately below so the
      // user is redirected to /gusts and sees the new clip there.
      if (!newPost.isGust) {
        const queryFilter = { queryKey: ["post-feed", "for-you"] };

        await queryClient.cancelQueries(queryFilter);

        queryClient.setQueriesData<InfiniteData<PostsPage, string | null>>(
          queryFilter,
          (oldData) => {
            if (!oldData?.pages[0]) {
              return oldData;
            }

            return {
              pageParams: oldData.pageParams,
              pages: [
                {
                  nextCursor: oldData.pages[0].nextCursor,
                  posts: [newPost, ...oldData.pages[0].posts],
                },
                ...oldData.pages.slice(1),
              ],
            };
          }
        );
      }

      queryClient.invalidateQueries({ queryKey: ["popularTags"] });
      if (newPost.isGust) {
        queryClient.invalidateQueries({ queryKey: ["gusts-feed"] });
        queryClient.invalidateQueries({ queryKey: ["explore-gusts-grid"] });
        queryClient.invalidateQueries({ queryKey: ["explore-top-gusts"] });
      }

      // Derivatives (posters, thumbs) are generated by the process job right
      // AFTER the row goes READY - the optimistically-prepended post starts
      // life without them. Re-pull the feeds twice so fresh thumbnails swap
      // in automatically instead of requiring a manual page refresh.
      const refreshFeeds = () => {
        void queryClient.invalidateQueries({
          queryKey: ["post-feed", "for-you"],
        });
        if (newPost.isGust) {
          void queryClient.invalidateQueries({ queryKey: ["gusts-feed"] });
        }
      };
      window.setTimeout(refreshFeeds, 4000);
      window.setTimeout(refreshFeeds, 12_000);
      const isHnShare = !!newPost.hnStoryShare;

      let description: string;
      let title: string;
      if (isHnShare) {
        description = "Your thoughts on this story are live";
        title = "Story Shared";
      } else if (newPost.isGust) {
        description = "Your gust is live, the feed's about to pop off!";
        title = "Gust Published";
      } else {
        description = "Your post is live, nice one!";
        title = "Post Published";
      }

      toast({
        description,
        duration: 5000,
        title,
      });
    },
  });

  return mutation;
}

export function useUpdateMentionsMutation(postId?: string) {
  // No changes needed here
  const { toast } = useToast();
  const queryClient = useQueryClient();

  return useMutation({
    mutationFn: async (mentions: string[]) => {
      if (!postId) {
        throw new Error("Post ID is required to update mentions");
      }
      const response = await updatePostMentions(postId, mentions);
      if (!response) {
        throw new Error("Failed to update mentions");
      }
      return response;
    },
    onError: (error) => {
      clientLog.error("Failed to update mentions:", error);
      toast({
        description: "Couldn't update mentions, try again?",
        variant: "destructive",
      });
    },
    onSuccess: (updatedPost) => {
      if (postId) {
        queryClient.setQueryData(["post", postId], updatedPost);
      }
      toast({
        description: "Everyone you mentioned has been notified",
        duration: 3000,
        title: "Mentions Updated",
      });
    },
  });
}
