// Logout jokes, copied verbatim from web
// (components/layouts/dialogs/constants/logout-messages.ts) so the native
// dialog reads exactly like its browser twin.
export const logoutJokes = [
  "Logging out? Don't forget to touch grass!",
  "See you later, code navigator!",
  "Taking a break from being awesome?",
  "Plot twist: User decides to go outside!",
  "Saving your progress... in real life!",
  "Remember to stay hydrated IRL!",
  "Disconnecting from the matrix...",
  "Time to face the final boss: Reality!",
  "Switching to offline mode...",
  "Error 418: I'm a teapot, but you're leaving!",
  "Ctrl + Alt + Defeat: Logging out detected!",
  "sudo goodbye --force",
  "git commit -m 'User.logout(): Gone touching grass'",
  "Error 418: I'm a teapot, but you're leaving!",
  "npm uninstall --save motivation",
  "while(true) { miss_you(); }",
  "Breaking news: Developer discovers world exists outside IDE!",
  "Plot twist: The real bug was the time you spent coding all along",
  "Switching from caffeine.js to reality.exe",
  "Successfully compiled touch_grass.exe",
  "Player 1 has left the server... to get a life!",
  "Game Over! Insert Social Life to continue...",
  "Achievement Unlocked: Touch Grass",
  "Saving progress... in real life!",
  "Breaking: Developer spotted using light mode... outside!",
  "Stack Overflow servers rejoice as you leave",
  "Your code is compiling... perfect time for a life!",
  "Keyboard needs a break from your angry typing",
  "Matrix connection terminated: Welcome to the real world!",
  "Houston, we have a logout!",
  "May the workforce be with you... always!",
  "Hasta la vista, developer!",
  "Time to debug your real-life relationships!",
  "Alert: Vitamin D deficiency needs attention!",
  "Warning: Outside temperature is not a boolean!",
  "Switching to human.exe, please wait...",
  "Coffee.java stopped working: Time for a real break!",
  "Warning: Caffeine levels critically low!",
  "Exception: CoffeeOverflowException at brain.java",
  "Time to reboot your coffee intake!",
  "Breaking: Developer remembers life exists outside VSCode!",
  "Status 201: New life created successfully!",
  "Deploying you to the real world...",
  "Runtime Exception: Life.exe needs attention!",
  "Plot twist: The WiFi password is 'goOutside'!",
  "Loading social_skills.exe... Please wait...",
  "Initiating human interaction protocol...",
  "Background process 'life.exe' needs attention!",
  "Remember to clear your cache... and your mind!",
  "Time to refresh more than just your browser!",
  "Your life is waiting for you to respond...",
  "Merge your work-life branches already!",
];

export const getRandomJoke = (): string =>
  logoutJokes[Math.floor(Math.random() * logoutJokes.length)] ?? "";
