import type { ConfigPlugin } from "expo/config-plugins";

import { ANDROID_SPLIT_ABIS } from "./abi-splits";

interface GradleModResults {
  contents: string;
  language: string;
  path: string;
}

interface AppBuildGradleModConfig {
  modResults: GradleModResults;
  modRequest?: Record<string, unknown>;
}

interface ExpoConfigWithMods {
  mods?: {
    android?: {
      appBuildGradle?: (
        config: AppBuildGradleModConfig
      ) => AppBuildGradleModConfig | Promise<AppBuildGradleModConfig>;
    };
  };
}

// The split itself is injected into the generated android/app/build.gradle. It
// has to be a plugin because apps/mobile/android is regenerated by
// `expo prebuild` and gitignored, so a hand edit to build.gradle would be
// silently discarded on the next prebuild.
//
// The ABI list and the reasoning behind it live in ./abi-splits, which the
// release build script reads too: with `universalApk false` the per-ABI file
// name is the only artifact the build produces, so the script that packages
// the release has to agree with this block about what is on disk.
const SPLITS_BLOCK = `    splits {
        abi {
            enable true
            reset()
            include ${ANDROID_SPLIT_ABIS.map((abi) => `'${abi}'`).join(", ")}
            universalApk false
        }
    }
`;

// Anchor on a block the Expo template always emits inside android {}. Injecting
// immediately before it keeps the result valid Groovy: a new sibling entry in
// the android block rather than text spliced into the middle of another one.
const ANCHOR = "    packagingOptions {";

// Registered by writing config.mods.android.appBuildGradle directly rather than
// through withAppBuildGradle(), which would mean depending on
// @expo/config-plugins just to inject one block into one generated file.
const withAndroidAbiSplits: ConfigPlugin = (config) => {
  const withMods = config as ExpoConfigWithMods;
  const androidMods = { ...withMods.mods?.android };
  const existingMod = androidMods.appBuildGradle;

  androidMods.appBuildGradle = async (modConfig) => {
    const next = existingMod ? await existingMod(modConfig) : modConfig;
    const results = next.modResults;

    if (results.language !== "groovy") {
      // Kotlin DSL is not used by this project. Bail rather than write Groovy
      // into a build.gradle.kts, which would fail at parse time.
      return next;
    }

    // Idempotent: prebuild can run repeatedly against a directory that was not
    // cleaned, and a second copy would be a nested-splits syntax error.
    if (results.contents.includes("universalApk")) {
      return next;
    }

    const anchorIndex = results.contents.indexOf(ANCHOR);
    if (anchorIndex === -1) {
      throw new Error(
        "withAndroidAbiSplits: could not find the packagingOptions block in " +
          "android/app/build.gradle. The Expo Android template changed, so the " +
          "insertion anchor needs updating."
      );
    }

    results.contents =
      results.contents.slice(0, anchorIndex) +
      SPLITS_BLOCK +
      results.contents.slice(anchorIndex);

    return next;
  };

  withMods.mods = { ...withMods.mods, android: androidMods };
  return withMods as typeof config;
};

export default withAndroidAbiSplits;
