// A local config plugin is loaded by @expo/require-utils, which compiles this
// file to a virtual .js module and then `require`s it. That require runs on
// Node's CommonJS resolver, which knows nothing about .ts: an extensionless
// relative import of a sibling TypeScript module fails with "Cannot find module"
// and takes the whole prebuild with it. Only `import type` is safe here, so
// this file has to stay self-contained - the split's ABI list lives here rather
// than beside it, and is exported for the release build script to read.
import type { ConfigPlugin } from "expo/config-plugins";

interface GradleModResults {
  contents: string;
  language: string;
  path: string;
}

interface AppBuildGradleModConfig {
  modResults: GradleModResults;
  modRequest?: Record<string, unknown>;
}

interface ExpoConfigWithMods {
  mods?: {
    android?: {
      appBuildGradle?: (
        config: AppBuildGradleModConfig
      ) => AppBuildGradleModConfig | Promise<AppBuildGradleModConfig>;
    };
  };
}

// The React Native native layer is the single largest thing in the Android
// build: lib/ measured 84.4 MB uncompressed across the four ABIs declared in
// gradle.properties, of which x86 (23.4 MB) and x86_64 (23.6 MB) are 47 MB that
// no real Android device can ever load. They exist only so the emulator can
// run, so shipping them inside a release APK makes every user download
// emulator-only code. An ABI split gives each APK exactly one ABI, so an arm64
// device downloads ~50 MB instead of ~112 MB.
//
// The x86_64 split is the one to `adb install` for emulator runs, so local
// development is unaffected. Google Play performs the equivalent split
// automatically from an AAB, so `bundleRelease` remains the right artifact for
// store distribution.

// Order is the order the Gradle `include` list is written in.
export const ANDROID_SPLIT_ABIS = [
  "armeabi-v7a",
  "arm64-v8a",
  "x86",
  "x86_64",
] as const;

export type AndroidSplitAbi = (typeof ANDROID_SPLIT_ABIS)[number];

/**
 * Whether a build is asking for an ABI the split actually produces. Gradle
 * would silently skip a split it does not know, so an unrecognised ABI has to
 * fail before a multi-minute build rather than after it.
 */
export function isAndroidSplitAbi(value: string): value is AndroidSplitAbi {
  return (ANDROID_SPLIT_ABIS as readonly string[]).includes(value);
}

/**
 * Where Gradle writes one ABI's release APK once the split is enabled. With
 * `universalApk false` there is no plain `app-release.apk` to fall back on: the
 * per-ABI file name is the only artifact the build produces, which is why the
 * build script that packages the release imports this from here.
 */
export function splitApkFileName(abi: string): string {
  return `app-${abi}-release.apk`;
}

// The split is injected into the generated android/app/build.gradle. It has to
// be a plugin because apps/mobile/android is regenerated by `expo prebuild` and
// gitignored, so a hand edit to build.gradle would be silently discarded on the
// next prebuild.
const SPLITS_BLOCK = `    splits {
        abi {
            enable true
            reset()
            include ${ANDROID_SPLIT_ABIS.map((abi) => `'${abi}'`).join(", ")}
            universalApk false
        }
    }
`;

// Anchor on a block the Expo template always emits inside android {}. Injecting
// immediately before it keeps the result valid Groovy: a new sibling entry in
// the android block rather than text spliced into the middle of another one.
const ANCHOR = "    packagingOptions {";

// Registered by writing config.mods.android.appBuildGradle directly rather than
// through withAppBuildGradle(), which would mean depending on
// @expo/config-plugins just to inject one block into one generated file.
const withAndroidAbiSplits: ConfigPlugin = (config) => {
  const withMods = config as ExpoConfigWithMods;
  const androidMods = { ...withMods.mods?.android };
  const existingMod = androidMods.appBuildGradle;

  androidMods.appBuildGradle = async (modConfig) => {
    const next = existingMod ? await existingMod(modConfig) : modConfig;
    const results = next.modResults;

    if (results.language !== "groovy") {
      // Kotlin DSL is not used by this project. Bail rather than write Groovy
      // into a build.gradle.kts, which would fail at parse time.
      return next;
    }

    // Idempotent: prebuild can run repeatedly against a directory that was not
    // cleaned, and a second copy would be a nested-splits syntax error.
    if (results.contents.includes("universalApk")) {
      return next;
    }

    const anchorIndex = results.contents.indexOf(ANCHOR);
    if (anchorIndex === -1) {
      throw new Error(
        "withAndroidAbiSplits: could not find the packagingOptions block in " +
          "android/app/build.gradle. The Expo Android template changed, so the " +
          "insertion anchor needs updating."
      );
    }

    results.contents =
      results.contents.slice(0, anchorIndex) +
      SPLITS_BLOCK +
      results.contents.slice(anchorIndex);

    return next;
  };

  withMods.mods = { ...withMods.mods, android: androidMods };
  return withMods as typeof config;
};

export default withAndroidAbiSplits;
