import { describe, expect, it } from "bun:test";
import { readFileSync } from "node:fs";

import withAndroidAbiSplits, {
  ANDROID_SPLIT_ABIS,
  isAndroidSplitAbi,
  splitApkFileName,
} from "./with-android-abi-splits";

// The plugin's own source, read for the loader constraint below - not this file.
const PLUGIN_URL = new URL("with-android-abi-splits.ts", import.meta.url);

// The android/ directory is generated by `expo prebuild` and gitignored, so this
// plugin is the only durable place the ABI split can live. A regression here
// means a 112 MB universal APK ships to users again, silently.
type AppBuildGradleMod = (config: {
  modResults: { contents: string; language: string; path: string };
}) => Promise<{ modResults: { contents: string } }>;

const template = `android {
    compileSdkVersion 36

    defaultConfig {
        applicationId "cc.asocialmedia.mobile"
    }

    packagingOptions {
        jniLibs {
            useLegacyPackaging false
        }
    }
}
`;

async function applyMod(contents: string, language = "groovy") {
  const config = withAndroidAbiSplits({ name: "t", slug: "t" } as never);
  // ExpoConfig does not type the mods bag, so read it through the same shape
  // the plugin writes into.
  const mod = (
    config as { mods?: { android?: { appBuildGradle?: AppBuildGradleMod } } }
  ).mods?.android?.appBuildGradle;
  if (!mod) {
    throw new Error("plugin did not register an appBuildGradle mod");
  }
  const next = await mod({
    modResults: { contents, language, path: "android/app/build.gradle" },
  });
  return next.modResults.contents;
}

describe("withAndroidAbiSplits", () => {
  it("injects an abi splits block into the android block", async () => {
    const result = await applyMod(template);
    expect(result).toContain("splits {");
    expect(result).toContain(
      "include 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'"
    );
    // The emulator ABIs must stay in the list, just in their own APK.
    expect(result).toContain("'x86_64'");
  });

  it("keeps every release ABI so no device loses support", async () => {
    const result = await applyMod(template);
    for (const abi of ["armeabi-v7a", "arm64-v8a", "x86", "x86_64"]) {
      expect(result).toContain(`'${abi}'`);
    }
  });

  it("disables the universal APK that carries every ABI at once", async () => {
    // universalApk true would keep producing the 112 MB artifact this plugin
    // exists to eliminate.
    expect(await applyMod(template)).toContain("universalApk false");
  });

  it("is idempotent, so a repeated prebuild cannot nest the block", async () => {
    const once = await applyMod(template);
    const twice = await applyMod(once);
    const thrice = await applyMod(twice);
    expect(twice).toBe(once);
    expect(thrice).toBe(once);
    expect((thrice.match(/splits \{/g) ?? []).length).toBe(1);
  });

  it("leaves the surrounding build.gradle intact", async () => {
    const result = await applyMod(template);
    expect(result).toContain('applicationId "cc.asocialmedia.mobile"');
    expect(result).toContain("useLegacyPackaging false");
    // The block goes in before packagingOptions, not in place of it.
    expect(result.indexOf("splits {")).toBeLessThan(
      result.indexOf("packagingOptions {")
    );
  });

  it("refuses to guess when the Expo template no longer has the anchor", async () => {
    // Silently doing nothing would ship a universal APK again with no error, so
    // a missing anchor has to be loud.
    await expect(
      applyMod("android {\n    compileSdkVersion 36\n}\n")
    ).rejects.toThrow(/packagingOptions/);
  });

  it("does not write Groovy into a Kotlin DSL build file", async () => {
    const kotlin = await applyMod(template, "kt");
    expect(kotlin).toBe(template);
  });

  it("carries no runtime import, because Expo's loader cannot resolve one", () => {
    // @expo/require-utils compiles this file to a virtual .js module and then
    // requires it, and that require runs on Node's CommonJS resolver, which
    // cannot resolve an extensionless relative import to a sibling .ts file.
    // Adding one does not fail a type check or this suite: it fails `expo
    // prebuild`, in CI, after the keystore has been provisioned. So the
    // constraint is asserted here instead of discovered there.
    const source = readFileSync(PLUGIN_URL, "utf-8");
    const runtimeImports = source
      .split("\n")
      .map((line, index) => ({ index: index + 1, line }))
      .filter(
        ({ line }) =>
          // `import type` is erased at compile time, so it never reaches the
          // resolver. Anything else that pulls a module in at runtime does.
          !/^\s*import\s+type\b/.test(line) &&
          (/^\s*import\s+[^(]/.test(line) || /\brequire\(\s*["']\./.test(line))
      );

    expect(runtimeImports).toEqual([]);
  });
});

describe("the split's ABI contract", () => {
  // The release build script imports these from this module - the plugin has to
  // stay import-free, so it cannot also be the only place the list lives. That
  // makes this file the single source of truth for both sides.
  it("names the four ABIs a release is split across", () => {
    expect(ANDROID_SPLIT_ABIS).toEqual([
      "armeabi-v7a",
      "arm64-v8a",
      "x86",
      "x86_64",
    ]);
  });

  it("accepts only an ABI the split produces", () => {
    expect(isAndroidSplitAbi("arm64-v8a")).toBe(true);
    expect(isAndroidSplitAbi("x86_64")).toBe(true);
    expect(isAndroidSplitAbi("arm64")).toBe(false);
    expect(isAndroidSplitAbi("")).toBe(false);
  });

  it("names the release APK the way Gradle writes it", () => {
    expect(splitApkFileName("arm64-v8a")).toBe("app-arm64-v8a-release.apk");
  });
});
