import type { ConfigPlugin } from "expo/config-plugins";

interface GradleModResults {
  contents: string;
  language: string;
  path: string;
}

interface AppBuildGradleModConfig {
  modResults: GradleModResults;
  modRequest?: Record<string, unknown>;
}

interface ExpoConfigWithMods {
  mods?: {
    android?: {
      appBuildGradle?: (
        config: AppBuildGradleModConfig
      ) => AppBuildGradleModConfig | Promise<AppBuildGradleModConfig>;
    };
  };
}

// The React Native native layer is the single largest thing in the Android
// build: lib/ measured 84.4 MB uncompressed across the four ABIs declared in
// gradle.properties, of which x86 (23.4 MB) and x86_64 (23.6 MB) are 47 MB that
// no real Android device can ever load. They exist only so the emulator can
// run, so shipping them inside a release APK makes every user download
// emulator-only code.
//
// This plugin injects an ABI split so each APK carries exactly one ABI: an
// arm64 device gets ~50 MB instead of ~112 MB. It has to be a plugin because
// apps/mobile/android is generated by `expo prebuild` and gitignored, so an
// edit to build.gradle would be silently discarded on the next prebuild.
//
// universalApk stays false on purpose: the 112 MB universal artifact is exactly
// what this exists to eliminate. The x86_64 split is the one to `adb install`
// for emulator runs, so local development is unaffected. Google Play performs
// the equivalent split automatically from an AAB, so `bundleRelease` remains the
// right artifact for store distribution.
const SPLITS_BLOCK = `    splits {
        abi {
            enable true
            reset()
            include 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'
            universalApk false
        }
    }
`;

// Anchor on a block the Expo template always emits inside android {}. Injecting
// immediately before it keeps the result valid Groovy: a new sibling entry in
// the android block rather than text spliced into the middle of another one.
const ANCHOR = "    packagingOptions {";

// Registered by writing config.mods.android.appBuildGradle directly rather than
// through withAppBuildGradle(), which would mean depending on
// @expo/config-plugins just to inject one block into one generated file.
const withAndroidAbiSplits: ConfigPlugin = (config) => {
  const withMods = config as ExpoConfigWithMods;
  const androidMods = { ...withMods.mods?.android };
  const existingMod = androidMods.appBuildGradle;

  androidMods.appBuildGradle = async (modConfig) => {
    const next = existingMod ? await existingMod(modConfig) : modConfig;
    const results = next.modResults;

    if (results.language !== "groovy") {
      // Kotlin DSL is not used by this project. Bail rather than write Groovy
      // into a build.gradle.kts, which would fail at parse time.
      return next;
    }

    // Idempotent: prebuild can run repeatedly against a directory that was not
    // cleaned, and a second copy would be a nested-splits syntax error.
    if (results.contents.includes("universalApk")) {
      return next;
    }

    const anchorIndex = results.contents.indexOf(ANCHOR);
    if (anchorIndex === -1) {
      throw new Error(
        "withAndroidAbiSplits: could not find the packagingOptions block in " +
          "android/app/build.gradle. The Expo Android template changed, so the " +
          "insertion anchor needs updating."
      );
    }

    results.contents =
      results.contents.slice(0, anchorIndex) +
      SPLITS_BLOCK +
      results.contents.slice(anchorIndex);

    return next;
  };

  withMods.mods = { ...withMods.mods, android: androidMods };
  return withMods as typeof config;
};

export default withAndroidAbiSplits;
